# Generated by Django 5.1.7 on 2025-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('warehouse admin', 'Warehouse Admin'), ('warehouse staff', 'Warehouse Staff'), ('manager', 'Manager'), ('employee', 'Employee'), ('engineering', 'Engineering'), ('OperationsMaintainance', 'operationsMaintainance'), ('budget analyst', 'Budget Analyst')], default='user', max_length=50),
        ),
    ]
