# Generated by Django 5.1.7 on 2025-04-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_role_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
