# Generated by Django 5.1.7 on 2025-04-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
