# Generated by Django 5.1.3 on 2025-05-03 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
