# Generated by Django 5.1.7 on 2025-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_rolerequestrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('warehouse_admin', 'Warehouse Admin'), ('warehouse_staff', 'Warehouse Staff'), ('manager', 'Manager'), ('employee', 'Employee'), ('engineering', 'Engineering'), ('operations_maintenance', 'Operations & Maintenance'), ('budget_analyst', 'Budget Analyst'), ('sub_office', 'Sub Office'), ('finance', 'Finance'), ('audit', 'Audit')], default='employee', max_length=50),
        ),
    ]
