# Generated by Django 5.1.7 on 2025-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('operations_maintenance', 'Operations & Maintenance'), ('finance', 'Finance'), ('admin', 'Admin')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='suboffice',
            field=models.CharField(blank=True, choices=[('sub_office_a', 'Sub Office A'), ('sub_office_b', 'Sub Office B'), ('sub_office_c', 'Sub Office C')], max_length=50, null=True),
        ),
    ]
