# Generated by Django 5.1.7 on 2025-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_user_department_user_id_image_url_user_suboffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='signature',
            field=models.URLField(blank=True, null=True),
        ),
    ]
