# Generated by Django 5.1.7 on 2025-05-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_materialrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeticket',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charge_ticket', to='requests.materialrequest'),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='material_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisition_voucher', to='requests.materialrequest'),
        ),
    ]
