# Generated by Django 5.1.7 on 2025-05-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountability',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
