# Generated by Django 5.1.7 on 2025-05-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_materialrequest_materialrequestitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='target_date',
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='actual_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='manpower',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='requester_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='target_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='work_order_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
