# Generated by Django 5.1.7 on 2025-05-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_materialrequest_target_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('charged', 'Charge Ticket Created'), ('requisitioned', 'Requisition Voucher Created'), ('partially_fulfilled', 'Partially Fulfilled'), ('invalid', 'Invalid'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
