# Generated by Django 5.1.7 on 2025-05-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_chargeticket_material_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('operations_maintainance', 'Operations & Maintenance'), ('finance', 'Finance')], max_length=50),
        ),
    ]
