# Generated by Django 5.1.7 on 2025-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0007_materialrequestitem_custom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeticket',
            name='approval_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chargeticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Fully Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
