# Generated by Django 5.1.7 on 2025-05-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0008_chargeticket_approval_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('operations_maintenance', 'Operations & Maintenance'), ('finance', 'Finance')], max_length=50),
        ),
    ]
