# Generated by Django 5.1.7 on 2025-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0009_alter_materialrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargeticket',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
