# Generated by Django 5.1.7 on 2025-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0010_chargeticket_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargeticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Fully Approved'), ('rejected', 'Rejected'), ('released', 'Released')], default='pending', max_length=20),
        ),
    ]
