# Generated by Django 5.1.7 on 2025-05-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0011_alter_chargeticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionvoucher',
            name='approval_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='requisitionvoucher',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
