# Generated by Django 5.1.7 on 2025-05-16 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0014_requisitionvoucher_rejected_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionvoucher',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rv_evaluator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitionvoucher',
            name='final_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rv_gm_approver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requisitionvoucher',
            name='recommended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rv_recommender', to=settings.AUTH_USER_MODEL),
        ),
    ]
