# Generated by Django 5.1.7 on 2025-05-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0016_purchaseorder_final_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
