# Generated by Django 5.1.7 on 2025-05-18 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_department'),
        ('requests', '0018_alter_purchaseorder_received_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('delivery_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('shortage', 'Shortage')], max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='requests.purchaseorder')),
            ],
        ),
    ]
