# Generated by Django 5.1.7 on 2025-05-19 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0019_deliveryrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='requests.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='QualityCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_certification', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True)),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.purchaseorderitem')),
                ('quality_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.qualitycheck')),
            ],
        ),
    ]
