# Generated by Django 5.1.7 on 2025-05-19 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0020_qualitycheck_qualitycheckitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('admin_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_admin_approved', to=settings.AUTH_USER_MODEL)),
                ('audit_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_audit_approved', to=settings.AUTH_USER_MODEL)),
                ('gm_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_gm_approved', to=settings.AUTH_USER_MODEL)),
                ('inspected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications_inspected', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='requests.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='CertifiedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('inspection_type', models.CharField(default='Brand Authenticity Specification Compliance', max_length=255)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.certification')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.purchaseorderitem')),
                ('quality_check_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certifieditem', to='requests.qualitycheckitem')),
            ],
        ),
    ]
