# Generated by Django 5.1.7 on 2025-05-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0022_certification_delivery_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='status',
            field=models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='started', max_length=20),
        ),
    ]
