# Generated by Django 5.1.7 on 2025-05-19 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_department'),
        ('requests', '0024_certification_rejected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_reports_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_report', to='requests.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='ReceivingReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.material')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.purchaseorderitem')),
                ('receiving_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='requests.receivingreport')),
            ],
        ),
    ]
