# Generated by Django 5.1.7 on 2025-05-20 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0025_receivingreport_receivingreportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivingreport',
            name='delivery_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_report', to='requests.deliveryrecord'),
        ),
    ]
