# Generated by Django 5.1.7 on 2025-05-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0026_receivingreport_delivery_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionitem',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requisitionitem',
            name='custom_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
