# Generated by Django 5.1.7 on 2025-05-24 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_department'),
        ('requests', '0027_requisitionitem_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.material'),
        ),
    ]
