# Generated by Django 5.1.7 on 2025-05-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0030_deliveryrecord_custom_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitycheckitem',
            name='remarks',
            field=models.CharField(blank=True),
        ),
    ]
