# Generated by Django 5.1.7 on 2025-05-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0032_alter_receivingreportitem_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitionvoucher',
            name='is_restocking',
            field=models.BooleanField(default=False),
        ),
    ]
