# Generated by Django 5.1.7 on 2025-05-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0033_requisitionvoucher_is_restocking'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
