# Generated by Django 5.1.7 on 2025-06-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0034_materialrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won_assigned', 'Work Order Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('charged', 'Charge Ticket Created'), ('requisitioned', 'Requisition Voucher Created'), ('partially_fulfilled', 'Partially Fulfilled'), ('invalid', 'Invalid'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
