# Generated by Django 5.1.7 on 2025-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0035_materialrequest_latitude_materialrequest_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('won_assigned', 'Work Order Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('charged', 'Charge Ticket Created'), ('ready_for_release', 'Ready for Release'), ('released', 'Released'), ('requisitioned', 'Requisition Voucher Created'), ('partially_fulfilled', 'Partially Fulfilled'), ('invalid', 'Invalid'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
