# Generated by Django 5.1.7 on 2025-05-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('operations_maintainance', 'Operations & Maintenance'), ('finance', 'Finance')], max_length=50),
        ),
    ]
