# Generated by Django 5.1.7 on 2025-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='department',
            field=models.CharField(choices=[('engineering', 'Engineering'), ('operations_maintenance', 'Operations & Maintenance'), ('finance', 'Finance')], max_length=50),
        ),
    ]
