# Generated by Django 5.1.7 on 2025-06-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('wiring', 'Wiring and Conductors'), ('poles', 'Poles and Supports'), ('metering', 'Metering Equipment'), ('transformers', 'Transformers and Substations Equipment'), ('hardware', 'Hardware and Fasteners'), ('safety', 'Safety Equipment'), ('tools', 'Tools and Accessories'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=32),
        ),
    ]
