# Generated by Django 5.1.7 on 2025-06-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_material_visible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('material',)},
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='department',
        ),
    ]
